services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mdd
    ports:
      - "3306:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: mdd_phpmyadmin_docker
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
    networks:
      - dev


volumes:
  data1-1:
networks:
  dev: